= ETX AI Delivery Workshop #2

== Agenda

Day 1 - Serving at Scale

* Advanced GPU Management
* Advanced vLLM
* Models as a Service

Day 2 - AI Agents

* todo

Day 3 - LLM Optimization and Inference

* todo

== Important Links

Here are some important links to help you on your journey:

* https://console-openshift-console.{openshift_cluster_ingress_domain}[OpenShift Web Console] 
* https://rhods-dashboard-redhat-ods-applications.{openshift_cluster_ingress_domain}[OpenShift AI Dashboard]
* https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}[Cluster Scoped ArgoCD]

== Important Credentials

The cluster admin user can be used to access all of the resources on the cluster including the ArgoCD instance and OpenShift AI Dashboard.

Cluster admin user: `{openshift_cluster_admin_username}`

Cluster admin password: `{openshift_cluster_admin_password}`

== Troubleshooting

=== CSR Approval

If you are having issues accessing the OpenShift Web Console you may need to approve the CSR for the cluster.

To approve the CSR, login to the bastion host using the credentials provided from demo.redhat.com and run the following command:

```bash
for i in `oc get csr | grep Pending | awk '{print $1}'`
do
    echo "Certificate [$i] needs approval"
    oc adm certificate approve $i
done
```

It may take a few minutes after the CSR approvals complete for the OpenShift Web Console to be accessible.
